#!/usr/bin/env bash

set -e

[[ -n "$(vgs)" ]] && vgs --noheadings -o vg_name | xargs -n1 vgremove -f
[[ -n "$(pvs)" ]] && pvs --noheadings -o pv_name | xargs -n1 pvremove -f

echo 'Setting up devices'
parted -s /dev/sda 'mklabel msdos' 'unit %' 'mkpart primary 0 100'
pvcreate /dev/sda1
vgcreate vg1 /dev/sda1

echo 'Setting up LVs'
lvcreate -L 6G -Wn -n root vg1
lvcreate -L 1G -Wn -n swap vg1
lvcreate -l 100%FREE -Wn -n data vg1
mkfs.btrfs --force /dev/vg1/root
mkswap /dev/vg1/swap
mkfs.btrfs --force /dev/vg1/data

echo 'Mounting devices'
mount /dev/vg1/root /mnt
swapon /dev/vg1/swap

echo 'Bootstrapping initial packages'
pacstrap /mnt base base-devel grub btrfs-progs puppet git
mkdir /mnt/srv/data
mount /dev/vg1/data /mnt/srv/data
genfstab -p /mnt >> /mnt/etc/fstab

echo 'Enabling lvm2 for mkinitcpio'
sed -i 's/^HOOKS="base udev/& lvm2/' /mnt/etc/mkinitcpio.conf
arch-chroot /mnt mkinitcpio -p linux

echo 'Setting up GRUB'
arch-chroot /mnt grub-install --recheck /dev/sda
arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg

echo 'Enabling initial networking'
arch-chroot /mnt systemctl enable dhcpcd

echo 'Setting the password'
password="$(head -c256 /dev/urandom | md5sum | head -c24)"
echo "root:$password" | arch-chroot /mnt chpasswd
echo "Root password is $password" >> /mnt/etc/issue

echo 'Bootstrap goblin'
arch-chroot /mnt git clone git://github.com/halyard/goblin /opt/goblin
cp /mnt/opt/goblin/meta/systemd/puppet-apply.service /mnt/etc/systemd/system/
cp /mnt/opt/goblin/meta/systemd/puppet-apply.timer /mnt/etc/systemd/system/
arch-chroot /mnt systemctl enable puppet-apply.timer

